
--Solution 1:
SELECT Root, End_Date FROM (SELECT Start_Date, End_Date, CONNECT_BY_ROOT Start_Date AS Root, LEVEL AS duration FROM Projects WHERE CONNECT_BY_ISLEAF = 1 CONNECT BY PRIOR End_Date = Start_Date) WHERE Root NOT IN (SELECT End_Date FROM Projects) ORDER BY duration, Root;

--Solution 2:
SELECT MIN(START_DATE),MAX(END_DATE) FROM ( SELECT *,(CAST(REPLACE(START_DATE,'-','') AS INT) -RN) AS GRP FROM (SELECT START_DATE,END_DATE,ROW_NUMBER() OVER (ORDER BY START_DATE ASC) AS RN FROM PROJECTS) T1 ) T2 GROUP BY GRP ORDER BY COUNT(1),MIN(START_DATE)

--Solution 3:
 SELECT A.START_DATE,B.END_DATE FROM (SELECT START_DATE,ROW_NUMBER() OVER (ORDER BY START_DATE) AS R FROM PROJECTS P1 WHERE NOT EXISTS (SELECT 1 FROM PROJECTS P2 WHERE P1.START_DATE=P2.END_DATE) ) A, (SELECT END_DATE,ROW_NUMBER() OVER (ORDER BY END_DATE) AS R FROM PROJECTS P1 WHERE NOT EXISTS (SELECT 1 FROM PROJECTS P2 WHERE P1.END_DATE=P2.START_DATE)) B WHERE A.R=B.R ORDER BY (B.END_DATE-A.START_DATE), A.START_DATE;
